/**
 * Liste des états pour les options du formulaire.
 * Chaque option contient la valeur, le label et l'abréviation de l'état.
 */


export const stateOptions = [
  { value: "Alabama", label: "Alabama", abbreviation: "AL" },
  { value: "Alaska", label: "Alaska", abbreviation: "AK" },
  { value: "Arizona", label: "Arizona", abbreviation: "AZ" },
  { value: "Arkansas", label: "Arkansas", abbreviation: "AR" },
  { value: "Californie", label: "Californie", abbreviation: "CA" },
  { value: "Caroline du Nord", label: "Caroline du Nord", abbreviation: "NC" },
  { value: "Caroline du Sud", label: "Caroline du Sud", abbreviation: "SC" },
  { value: "Colorado", label: "Colorado", abbreviation: "CO" },
  { value: "Connecticut", label: "Connecticut", abbreviation: "CT" },
  { value: "Dakota du Nord", label: "Dakota du Nord", abbreviation: "ND" },
  { value: "Dakota du Sud", label: "Dakota du Sud", abbreviation: "SD" },
  { value: "Delaware", label: "Delaware", abbreviation: "DE" },
  { value: "Floride", label: "Floride", abbreviation: "FL" },
  { value: "Géorgie", label: "Géorgie", abbreviation: "GA" },
  { value: "Hawaï", label: "Hawaï", abbreviation: "HI" },
  { value: "Idaho", label: "Idaho", abbreviation: "ID" },
  { value: "Illinois", label: "Illinois", abbreviation: "IL" },
  { value: "Indiana", label: "Indiana", abbreviation: "IN" },
  { value: "Iowa", label: "Iowa", abbreviation: "IA" },
  { value: "Kansas", label: "Kansas", abbreviation: "KS" },
  { value: "Kentucky", label: "Kentucky", abbreviation: "KY" },
  { value: "Louisiane", label: "Louisiane", abbreviation: "LA" },
  { value: "Maine", label: "Maine", abbreviation: "ME" },
  { value: "Maryland", label: "Maryland", abbreviation: "MD" },
  { value: "Massachusetts", label: "Massachusetts", abbreviation: "MA" },
  { value: "Michigan", label: "Michigan", abbreviation: "MI" },
  { value: "Minnesota", label: "Minnesota", abbreviation: "MN" },
  { value: "Mississippi", label: "Mississippi", abbreviation: "MS" },
  { value: "Missouri", label: "Missouri", abbreviation: "MO" },
  { value: "Montana", label: "Montana", abbreviation: "MT" },
  { value: "Nebraska", label: "Nebraska", abbreviation: "NE" },
  { value: "Nevada", label: "Nevada", abbreviation: "NV" },
  { value: "New Hampshire", label: "New Hampshire", abbreviation: "NH" },
  { value: "New Jersey", label: "New Jersey", abbreviation: "NJ" },
  { value: "Nouveau-Mexique", label: "Nouveau-Mexique", abbreviation: "NM" },
  { value: "New York", label: "New York", abbreviation: "NY" },
  { value: "Ohio", label: "Ohio", abbreviation: "OH" },
  { value: "Oklahoma", label: "Oklahoma", abbreviation: "OK" },
  { value: "Oregon", label: "Oregon", abbreviation: "OR" },
  { value: "Pennsylvanie", label: "Pennsylvanie", abbreviation: "PA" },
  { value: "Rhode Island", label: "Rhode Island", abbreviation: "RI" },
  { value: "Tennessee", label: "Tennessee", abbreviation: "TN" },
  { value: "Texas", label: "Texas", abbreviation: "TX" },
  { value: "Utah", label: "Utah", abbreviation: "UT" },
  { value: "Vermont", label: "Vermont", abbreviation: "VT" },
  { value: "Virginie", label: "Virginie", abbreviation: "VA" },
  { value: "Virginie-Occidentale", label: "Virginie-Occidentale", abbreviation: "WV" },
  { value: "Washington", label: "Washington", abbreviation: "WA" },
  { value: "Wisconsin", label: "Wisconsin", abbreviation: "WI" },
  { value: "Wyoming", label: "Wyoming", abbreviation: "WY" },  ];
  